### ISSUE TITLE
save log in html format

### ISSUE THREAD

**Issue by lacroutelacroute** [CoolerVoid/0d1n#31]
hello pro

with this command line
sudo ./0d1n --host "http://www.localhost/-locations.jsp?sort=^"  --payloads  payloads/xss_robertux.txt     --log log123test --save_response

the log is saved in texte format
hos to save the log in html format

**Comment by LaurianoElmiroDuarte** [comment]
did you solved ?

**Comment by CoolerVoid** [comment]
You can view result at datatables, html+css+javascript...

At the future the todo is LaTex report...
