### ISSUE TITLE
Error on make: multiple definition of (param) and first defined here

### ISSUE THREAD

**Issue by avancerapide** [CoolerVoid/0d1n#37]
Hello,
On Ubuntu groovy, I install the prerequisite libcurl4-gnutls-dev (I don't find  libcurl-dev)

when I launch make, I have this message (sorry in French):

```
gcc -W -Wall -Wextra -Wformat-security -fstack-protector-all -pie -fPIE -c src/*.c -Isrc/headers/
gcc -fstack-protector-all -pie -fPIE  -o bin/0d1n *.o  -Wl,-z,relro,-z,now -lcurl -lpthread
/usr/bin/ld : file_ops.o:(.bss+0x0) : définitions multiples de « param »; 0d1n.o:(.bss+0x0) : défini pour la première fois ici
/usr/bin/ld : get_csrf_token.o:(.bss+0x0) : définitions multiples de « param »; 0d1n.o:(.bss+0x0) : défini pour la première fois ici
/usr/bin/ld : opt_extract.o:(.bss+0x0) : définitions multiples de « param »; 0d1n.o:(.bss+0x0) : défini pour la première fois ici
/usr/bin/ld : results.o:(.bss+0x0) : définitions multiples de « param »; 0d1n.o:(.bss+0x0) : défini pour la première fois ici
/usr/bin/ld : scan.o:(.bss+0x0) : définitions multiples de « param »; 0d1n.o:(.bss+0x0) : défini pour la première fois ici
/usr/bin/ld : spider.o:(.bss+0x0) : définitions multiples de « param »; 0d1n.o:(.bss+0x0) : défini pour la première fois ici
collect2: error: ld returned 1 exit status
make: *** [Makefile:21 : 0d1n] Erreur 1
```

I try with v3.4, v3.2, v3.1 of 0d1n and I have the same messages.

What I have been missing ?

Thanks

**Comment by CoolerVoid** [comment]
Current tested in:
```
$ uname -a; gcc -v
Linux ubuntu 4.15.0-126-generic #129-Ubuntu SMP Mon Nov 23 18:53:38 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.5.0-3ubuntu1~18.04' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04) 
```
Sir relax,
I gonna install Ubuntu groovy, and test here compile process, if have this error i can make a patch fix.

thank you for warning

cheers

**Comment by Biedubbeljoe** [comment]
Same error in Kali:
kali@kali:~/0d1n$ uname -a; gcc -v
Linux kali 5.9.0-kali4-amd64 #1 SMP Debian 5.9.11-1kali1 (2020-12-01) x86_64 GNU/Linux
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/10/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 10.2.0-19' --with-bugurl=file:///usr/share/doc/gcc-10/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-10 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-10-Pzlurt/gcc-10-10.2.0/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-10-Pzlurt/gcc-10-10.2.0/debian/tmp-gcn/usr,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-mutex
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 10.2.0 (Debian 10.2.0-19) 

--------------------------------------------------
kali@kali:~/0d1n$ sudo make
gcc -W -Wall -Wextra -Wformat-security -fstack-protector-all -pie -fPIE -c src/*.c -Isrc/headers/
gcc -fstack-protector-all -pie -fPIE  -o bin/0d1n *.o  -Wl,-z,relro,-z,now -lcurl -lpthread
/usr/bin/ld: file_ops.o:(.bss+0x0): multiple definition of `param'; 0d1n.o:(.bss+0x0): first defined here
/usr/bin/ld: get_csrf_token.o:(.bss+0x0): multiple definition of `param'; 0d1n.o:(.bss+0x0): first defined here
/usr/bin/ld: opt_extract.o:(.bss+0x0): multiple definition of `param'; 0d1n.o:(.bss+0x0): first defined here
/usr/bin/ld: results.o:(.bss+0x0): multiple definition of `param'; 0d1n.o:(.bss+0x0): first defined here
/usr/bin/ld: scan.o:(.bss+0x0): multiple definition of `param'; 0d1n.o:(.bss+0x0): first defined here
/usr/bin/ld: spider.o:(.bss+0x0): multiple definition of `param'; 0d1n.o:(.bss+0x0): first defined here
collect2: error: ld returned 1 exit status
make: *** [Makefile:21: 0d1n] Error 1

**Comment by CoolerVoid** [comment]
Sorry, try again, "git clone..." , i make new patch to run in GCC v10
https://github.com/CoolerVoid/0d1n/releases/tag/OdinV35

thanks for warning sirs

cheers

**Comment by avancerapide** [comment]
Yes !
it works !

Thanks a lot

**Comment by AntonioCosta-mb** [comment]
So remember gcc 10 is not stable, i make some test here with gcc version 10, have a mistake in compiler because pthreads not work in 0d1n, i recommend version 7 or 8 of GCC.

https://trofi.github.io/posts/213-gcc-10-in-gentoo.html
new versions always have a lot bugs...

**Comment by CoolerVoid** [comment]
@avancerapide @Biedubbeljoe 
So remember gcc 10 is not stable, i make some test here with gcc version 10, run but have a mistake in compiler because pthreads not work in 0d1n, i recommend version 7 or 8 of GCC, that version run with pthreads without bugs.

One path to solve, u can install "apt-get install gcc-7", and change name of compiler in Makefile replace first line gcc to gcc-7(bin name of version 7)...

https://trofi.github.io/posts/213-gcc-10-in-gentoo.html
new versions of GCC always have a lot bugs...

Kali users use 90% of tools in interpreted languages like python, ruby... its more harder to get dynamic low level bugs...

**Comment by Biedubbeljoe** [comment]
Thanks for this CoolerVoid. Maybe it is an idea to script this, install gcc-7 and revert to it, as this solve the problem.Now most will see a faulty install and will not use this tool. Great work, 😊On Dec 25, 2020 4:24 AM, Cooler_ <notifications@github.com> wrote:
@avancerapide @Biedubbeljoe
So remember gcc 10 is not stable, i make some test here with gcc version 10, run but have a mistake in compiler because pthreads not work in 0d1n, i recommend version 7 or 8 of GCC, that version run with pthreads without bugs.
One path to solve, u can install "apt-get install gcc-7", and change name of compiler in Makefile replace first line gcc to gcc-7(bin name of version 7)...
https://trofi.github.io/posts/213-gcc-10-in-gentoo.html
new versions of GCC always have a lot bugs...
Kali users use 90% of tools in interpreted languages like python, ruby... its more harder to get dynamic low level bugs...
