### ISSUE TITLE
SSL error - Invalid SSL cert

### ISSUE THREAD

**Issue by Biedubbeljoe** [CoolerVoid/0d1n#39]
kali@kali:~/0d1n/0d1n_viewer$ bin/0d1n_view
Starting SSL server on port 40111, cert from /opt/0d1n/server/cert/certkey.pem, key from /opt/0d1n/server/cert/privateKey.key

--- DEBUG-START ---

 Mon Jan  4 15:08:03 2021 src/0d1n_view.c[64] main(): 
Failed to create listener: Invalid SSL cert

--- DEBUG-END ---

How can I fix this error?

**Comment by CoolerVoid** [comment]
Interesting, so try this following:
```
$ cd cert; openssl req -x509 -sha256 -nodes -days 365 -newkey rsa:2048 -keyout privateKey.key -out certificate.crt

$ cat certificate.crt privateKey.key > certkey.pem
$ cp certkey.pem /opt/0d1n/server/cert/; cp provateKey.key /opt/0d1n/server/cert/

```
