### ISSUE TITLE
install failed

### ISSUE THREAD

**Issue by 0xhunster** [CoolerVoid/0d1n#41]
![image](https://user-images.githubusercontent.com/46501627/172569945-1aa8500c-4d60-48e4-a1ba-8fbeac84c85f.png)

**Comment by CoolerVoid** [comment]
Please install the libcurl
https://curl.se/libcurl/c/CURLINFO_TOTAL_TIME_T.html
```
$ sudo apt-get install libcurl-dev
or try libcurl4-de or libcurl*

if rpm distro

$ sudo yum install libcurl-devel
```

**Comment by 0xhunster** [comment]
Hello,
sorry for the delay,

here are my screenshots

![image](https://user-images.githubusercontent.com/46501627/174489958-b9b0348d-9ba1-4476-b4e3-7be3c3146fcb.png)
